[package]
name          = "utils"
description   = "Definition and types for the CoolCat managers"
version       = { workspace = true }
edition       = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[dependencies]
cosmwasm-schema             = { workspace = true }
cosmwasm-std                = { workspace = true }
cw-utils                    = { workspace = true }
schemars                    = { workspace = true }
serde                       = { workspace = true }
cw721-base                  = { workspace = true, features = ["library"] }
